# Get all blog articles
GET http://localhost:3003/api/blogs
###

# Create new article
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The best programming language",
    "author": "Axda",
    "url": "http://localhost:3003/api/blogs/1",
    "likes": 0
}